name: Deploy Angular to gh-pages branch

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# This permission is essential to allow the action to push to the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build -- --base-href /Simonalbi/

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/Simonalbi/browser
          publish_branch: gh-pages
